'on':
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: atomicjar/testcontainers-cloud-setup-action@main
      if: env.TC_CLOUD_TOKEN != ''
      env:
        TC_CLOUD_TOKEN: ${{ secrets.TC_CLOUD_TOKEN }}

    - run: |-
        ulimit -n 16000
        nix-shell --run "pytest"
